site_name: Cyber Security Notes
site_url: https://reizu.mirei.se
site_author: reizu
repo_name: reizu-x/SOC-Notes
repo_url: https://github.com/reizu-x/SOC-Notes

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Coda Caption
  icon:
    logo: material/notebook-plus
    annotation: material/arrow-right-circle-outline
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light Mode
      primary: amber
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark Mode
      primary: blue
      accent: deep purple

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Cert List: cert.md

  - General Notes:
    - Notes:
      - Cheat Sheets:
        - PowerShell: General Notes/Notes/Cheat Sheets/powershell.md
        - PowerShell Hex: General Notes/Notes/Cheat Sheets/powershell-hex.md
      - Templates:
        - Phishing Template: General Notes/Notes/Templates/phishing-template.md
    - Links:
      - Tools: General Notes/Links/Tools/tools.md
      - Blogs: General Notes/Links/Blogs/blogs.md
      - Archives: General Notes/Links/Tools/archive.md

  - Blue Team:
    - Notes: Blue Team/notes.md
    - Links: Blue Team/bt-tools.md

  - Red Team:
    - Notes: Red Team/notes.md
    - Links: Red Team/rt-tools.md

  - Detection Engineering:
    - Notes: Detection Engineering/notes.md
    - Process: Detection Engineering/process.md
    - Tools: Detection Engineering/de-tools.md
    - Sigma: Detection Engineering/sigma.md
  
  - Programming:
    - Links: Programming/code-links.md
    - Python: Programming/python.md
    - C++: Programming/c++.md

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/